
// This file is autogenerated

#include "config.hpp"
#include "geometry2d.hpp"

#define AUTO_TEST(n) res=n<R>(s); if(res) return res;

namespace geometry2d {
template<typename R> int auto_tests(std::ostream& s) {
  int res=0;
  AUTO_TEST(test_vec2_basic);
  AUTO_TEST(test_vec2_rotate);

  return 0;

}
} // namespace geometry2d

// ALL DONE

