name: CI
on:
  push:
    branches:
    - main
    - release/*
  workflow_dispatch:
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # build all using cmake        
      - name: build
        run: |
          sudo apt-get -y install catch2
          mkdir build
          cd build
          cmake ..
          cmake --build . --config Release
          sudo make install
          make test
